/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment {
  'content' : string,
  'createdAt' : Time,
  'authorName' : [] | [string],
  'author' : Principal,
  'postId' : bigint,
}
export interface Event {
  'id' : bigint,
  'startTime' : Time,
  'title' : string,
  'endTime' : Time,
  'createdAt' : Time,
  'authorName' : [] | [string],
  'description' : string,
  'author' : Principal,
  'location' : string,
}
export type ExternalBlob = Uint8Array;
export interface FollowCounts { 'followers' : bigint, 'following' : bigint }
export interface ImageAttachment {
  'contentType' : string,
  'bytes' : Uint8Array,
}
export interface LegacyPost {
  'id' : bigint,
  'title' : string,
  'body' : string,
  'createdAt' : Time,
  'authorName' : [] | [string],
  'author' : Principal,
  'image' : [] | [ImageAttachment],
}
export interface Link { 'url' : string, 'displayName' : string }
export type Time = bigint;
export interface UserProfile {
  'bio' : string,
  'displayName' : string,
  'plushieImages' : Array<ExternalBlob>,
  'links' : Array<Link>,
  'publicDirectory' : boolean,
  'avatar' : [] | [ExternalBlob],
}
export interface UserProfileEdit {
  'bio' : string,
  'displayName' : string,
  'plushieImages' : Array<ExternalBlob>,
  'links' : Array<Link>,
  'publicDirectory' : boolean,
  'avatar' : [] | [ExternalBlob],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createComment' : ActorMethod<[bigint, [] | [string], string], Comment>,
  'createEvent' : ActorMethod<
    [[] | [string], string, string, string, Time, Time],
    bigint
  >,
  'createPost' : ActorMethod<
    [[] | [string], string, string, [] | [Uint8Array], [] | [string]],
    bigint
  >,
  'deletePost' : ActorMethod<[bigint], undefined>,
  'doesCallerFollow' : ActorMethod<[Principal], boolean>,
  'editPost' : ActorMethod<[bigint, string, string, [] | [string]], undefined>,
  'follow' : ActorMethod<[Principal], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCommentCounts' : ActorMethod<[Array<bigint>], Array<[bigint, bigint]>>,
  'getComments' : ActorMethod<[bigint], Array<Comment>>,
  'getEvent' : ActorMethod<[bigint], Event>,
  'getFollowCounts' : ActorMethod<[Principal], FollowCounts>,
  'getPost' : ActorMethod<[bigint], LegacyPost>,
  'getPostLikeCount' : ActorMethod<[bigint], bigint>,
  'getProfileLikeCount' : ActorMethod<[Principal], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isPostLikedByCaller' : ActorMethod<[bigint], boolean>,
  'isProfileLikedByCaller' : ActorMethod<[Principal], boolean>,
  'likePost' : ActorMethod<[bigint], undefined>,
  'likeProfile' : ActorMethod<[Principal], undefined>,
  'listDirectoryProfiles' : ActorMethod<[], Array<UserProfile>>,
  'listEvents' : ActorMethod<[], Array<Event>>,
  'listPosts' : ActorMethod<[], Array<LegacyPost>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfileEdit], undefined>,
  'unfollow' : ActorMethod<[Principal], undefined>,
  'unlikePost' : ActorMethod<[bigint], undefined>,
  'unlikeProfile' : ActorMethod<[Principal], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];