/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Post = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'createdAt' : Time,
  'authorName' : IDL.Opt(IDL.Text),
  'author' : IDL.Principal,
});

export const idlService = IDL.Service({
  'createPost' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'getPost' : IDL.Func([IDL.Nat], [Post], ['query']),
  'listPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Post = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'createdAt' : Time,
    'authorName' : IDL.Opt(IDL.Text),
    'author' : IDL.Principal,
  });
  
  return IDL.Service({
    'createPost' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'getPost' : IDL.Func([IDL.Nat], [Post], ['query']),
    'listPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };