/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Comment = IDL.Record({
  'content' : IDL.Text,
  'createdAt' : Time,
  'authorName' : IDL.Opt(IDL.Text),
  'author' : IDL.Principal,
  'postId' : IDL.Nat,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const PollOption = IDL.Record({
  'optionId' : IDL.Nat,
  'text' : IDL.Text,
});
export const PostEdit = IDL.Record({
  'title' : IDL.Text,
  'video' : IDL.Opt(ExternalBlob),
  'body' : IDL.Text,
  'authorName' : IDL.Opt(IDL.Text),
});
export const Link = IDL.Record({ 'url' : IDL.Text, 'displayName' : IDL.Text });
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'displayName' : IDL.Text,
  'plushieImages' : IDL.Vec(ExternalBlob),
  'links' : IDL.Vec(Link),
  'publicDirectory' : IDL.Bool,
  'avatar' : IDL.Opt(ExternalBlob),
});
export const Event = IDL.Record({
  'id' : IDL.Nat,
  'startTime' : Time,
  'title' : IDL.Text,
  'endTime' : Time,
  'createdAt' : Time,
  'authorName' : IDL.Opt(IDL.Text),
  'description' : IDL.Text,
  'author' : IDL.Principal,
  'location' : IDL.Text,
});
export const FollowCounts = IDL.Record({
  'followers' : IDL.Nat,
  'following' : IDL.Nat,
});
export const ModerationOutcome = IDL.Variant({
  'allow' : IDL.Null,
  'manualReview' : IDL.Null,
  'block' : IDL.Null,
});
export const ModeratedContent = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'moderationOutcome' : ModerationOutcome,
  'video' : IDL.Opt(ExternalBlob),
  'body' : IDL.Text,
  'submittedAt' : Time,
  'author' : IDL.Principal,
});
export const Poll = IDL.Record({
  'question' : IDL.Text,
  'createdAt' : Time,
  'createdBy' : IDL.Principal,
  'isActive' : IDL.Bool,
  'options' : IDL.Vec(PollOption),
  'pollId' : IDL.Nat,
});
export const PollWithResults = IDL.Record({
  'question' : IDL.Text,
  'createdAt' : Time,
  'createdBy' : IDL.Principal,
  'results' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)),
  'isActive' : IDL.Bool,
  'options' : IDL.Vec(PollOption),
  'pollId' : IDL.Nat,
});
export const Post = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'video' : IDL.Opt(ExternalBlob),
  'body' : IDL.Text,
  'createdAt' : Time,
  'authorName' : IDL.Opt(IDL.Text),
  'author' : IDL.Principal,
});
export const PostWithCounts = IDL.Record({
  'likeCount' : IDL.Nat,
  'post' : Post,
  'commentCount' : IDL.Nat,
});
export const SupporterRequest = IDL.Record({
  'displayName' : IDL.Text,
  'submittedAt' : Time,
  'numberOfCoffees' : IDL.Opt(IDL.Nat),
  'message' : IDL.Text,
  'validUntil' : IDL.Opt(Time),
});
export const SupporterProfile = IDL.Record({
  'displayName' : IDL.Text,
  'addedAt' : Time,
  'validUntil' : IDL.Opt(Time),
});
export const UserProfileEdit = IDL.Record({
  'bio' : IDL.Text,
  'displayName' : IDL.Text,
  'plushieImages' : IDL.Vec(ExternalBlob),
  'links' : IDL.Vec(Link),
  'publicDirectory' : IDL.Bool,
  'avatar' : IDL.Opt(ExternalBlob),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approveModerationRequest' : IDL.Func([IDL.Nat], [], []),
  'approveSupporter' : IDL.Func([IDL.Principal, IDL.Opt(Time)], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createComment' : IDL.Func(
      [IDL.Nat, IDL.Opt(IDL.Text), IDL.Text],
      [Comment],
      [],
    ),
  'createEvent' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Text, IDL.Text, IDL.Text, Time, Time],
      [IDL.Nat],
      [],
    ),
  'createModerationRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
      [IDL.Nat],
      [],
    ),
  'createPoll' : IDL.Func([IDL.Text, IDL.Vec(PollOption)], [IDL.Nat], []),
  'deletePost' : IDL.Func([IDL.Nat], [], []),
  'doesCallerFollow' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'editPost' : IDL.Func([IDL.Nat, PostEdit], [], []),
  'follow' : IDL.Func([IDL.Principal], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCommentCounts' : IDL.Func(
      [IDL.Vec(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat))],
      ['query'],
    ),
  'getComments' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
  'getEvent' : IDL.Func([IDL.Nat], [Event], ['query']),
  'getFollowCounts' : IDL.Func([IDL.Principal], [FollowCounts], ['query']),
  'getModerationQueue' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, ModeratedContent))],
      ['query'],
    ),
  'getPoll' : IDL.Func([IDL.Nat], [Poll], ['query']),
  'getPollResults' : IDL.Func([IDL.Nat], [PollWithResults], ['query']),
  'getPost' : IDL.Func([IDL.Nat], [Post], ['query']),
  'getPostLikeCount' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
  'getPostsWithCounts' : IDL.Func([], [IDL.Vec(PostWithCounts)], ['query']),
  'getProfileLikeCount' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'getSupporterRequests' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, SupporterRequest))],
      ['query'],
    ),
  'getSupporters' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, SupporterProfile))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isPostLikedByCaller' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'isProfileLikedByCaller' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'likePost' : IDL.Func([IDL.Nat], [], []),
  'likeProfile' : IDL.Func([IDL.Principal], [], []),
  'listDirectoryProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'listEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'listPolls' : IDL.Func([], [IDL.Vec(Poll)], ['query']),
  'listPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'rejectModerationRequest' : IDL.Func([IDL.Nat], [], []),
  'revokeSupporter' : IDL.Func([IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfileEdit], [], []),
  'submitSupporterRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Nat), IDL.Opt(Time)],
      [],
      [],
    ),
  'unfollow' : IDL.Func([IDL.Principal], [], []),
  'unlikePost' : IDL.Func([IDL.Nat], [], []),
  'unlikeProfile' : IDL.Func([IDL.Principal], [], []),
  'vote' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Comment = IDL.Record({
    'content' : IDL.Text,
    'createdAt' : Time,
    'authorName' : IDL.Opt(IDL.Text),
    'author' : IDL.Principal,
    'postId' : IDL.Nat,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const PollOption = IDL.Record({ 'optionId' : IDL.Nat, 'text' : IDL.Text });
  const PostEdit = IDL.Record({
    'title' : IDL.Text,
    'video' : IDL.Opt(ExternalBlob),
    'body' : IDL.Text,
    'authorName' : IDL.Opt(IDL.Text),
  });
  const Link = IDL.Record({ 'url' : IDL.Text, 'displayName' : IDL.Text });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'displayName' : IDL.Text,
    'plushieImages' : IDL.Vec(ExternalBlob),
    'links' : IDL.Vec(Link),
    'publicDirectory' : IDL.Bool,
    'avatar' : IDL.Opt(ExternalBlob),
  });
  const Event = IDL.Record({
    'id' : IDL.Nat,
    'startTime' : Time,
    'title' : IDL.Text,
    'endTime' : Time,
    'createdAt' : Time,
    'authorName' : IDL.Opt(IDL.Text),
    'description' : IDL.Text,
    'author' : IDL.Principal,
    'location' : IDL.Text,
  });
  const FollowCounts = IDL.Record({
    'followers' : IDL.Nat,
    'following' : IDL.Nat,
  });
  const ModerationOutcome = IDL.Variant({
    'allow' : IDL.Null,
    'manualReview' : IDL.Null,
    'block' : IDL.Null,
  });
  const ModeratedContent = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'moderationOutcome' : ModerationOutcome,
    'video' : IDL.Opt(ExternalBlob),
    'body' : IDL.Text,
    'submittedAt' : Time,
    'author' : IDL.Principal,
  });
  const Poll = IDL.Record({
    'question' : IDL.Text,
    'createdAt' : Time,
    'createdBy' : IDL.Principal,
    'isActive' : IDL.Bool,
    'options' : IDL.Vec(PollOption),
    'pollId' : IDL.Nat,
  });
  const PollWithResults = IDL.Record({
    'question' : IDL.Text,
    'createdAt' : Time,
    'createdBy' : IDL.Principal,
    'results' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)),
    'isActive' : IDL.Bool,
    'options' : IDL.Vec(PollOption),
    'pollId' : IDL.Nat,
  });
  const Post = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'video' : IDL.Opt(ExternalBlob),
    'body' : IDL.Text,
    'createdAt' : Time,
    'authorName' : IDL.Opt(IDL.Text),
    'author' : IDL.Principal,
  });
  const PostWithCounts = IDL.Record({
    'likeCount' : IDL.Nat,
    'post' : Post,
    'commentCount' : IDL.Nat,
  });
  const SupporterRequest = IDL.Record({
    'displayName' : IDL.Text,
    'submittedAt' : Time,
    'numberOfCoffees' : IDL.Opt(IDL.Nat),
    'message' : IDL.Text,
    'validUntil' : IDL.Opt(Time),
  });
  const SupporterProfile = IDL.Record({
    'displayName' : IDL.Text,
    'addedAt' : Time,
    'validUntil' : IDL.Opt(Time),
  });
  const UserProfileEdit = IDL.Record({
    'bio' : IDL.Text,
    'displayName' : IDL.Text,
    'plushieImages' : IDL.Vec(ExternalBlob),
    'links' : IDL.Vec(Link),
    'publicDirectory' : IDL.Bool,
    'avatar' : IDL.Opt(ExternalBlob),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approveModerationRequest' : IDL.Func([IDL.Nat], [], []),
    'approveSupporter' : IDL.Func([IDL.Principal, IDL.Opt(Time)], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createComment' : IDL.Func(
        [IDL.Nat, IDL.Opt(IDL.Text), IDL.Text],
        [Comment],
        [],
      ),
    'createEvent' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Text, IDL.Text, IDL.Text, Time, Time],
        [IDL.Nat],
        [],
      ),
    'createModerationRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
        [IDL.Nat],
        [],
      ),
    'createPoll' : IDL.Func([IDL.Text, IDL.Vec(PollOption)], [IDL.Nat], []),
    'deletePost' : IDL.Func([IDL.Nat], [], []),
    'doesCallerFollow' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'editPost' : IDL.Func([IDL.Nat, PostEdit], [], []),
    'follow' : IDL.Func([IDL.Principal], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCommentCounts' : IDL.Func(
        [IDL.Vec(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat))],
        ['query'],
      ),
    'getComments' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
    'getEvent' : IDL.Func([IDL.Nat], [Event], ['query']),
    'getFollowCounts' : IDL.Func([IDL.Principal], [FollowCounts], ['query']),
    'getModerationQueue' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, ModeratedContent))],
        ['query'],
      ),
    'getPoll' : IDL.Func([IDL.Nat], [Poll], ['query']),
    'getPollResults' : IDL.Func([IDL.Nat], [PollWithResults], ['query']),
    'getPost' : IDL.Func([IDL.Nat], [Post], ['query']),
    'getPostLikeCount' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
    'getPostsWithCounts' : IDL.Func([], [IDL.Vec(PostWithCounts)], ['query']),
    'getProfileLikeCount' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'getSupporterRequests' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, SupporterRequest))],
        ['query'],
      ),
    'getSupporters' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, SupporterProfile))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isPostLikedByCaller' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'isProfileLikedByCaller' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'likePost' : IDL.Func([IDL.Nat], [], []),
    'likeProfile' : IDL.Func([IDL.Principal], [], []),
    'listDirectoryProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'listEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'listPolls' : IDL.Func([], [IDL.Vec(Poll)], ['query']),
    'listPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'rejectModerationRequest' : IDL.Func([IDL.Nat], [], []),
    'revokeSupporter' : IDL.Func([IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfileEdit], [], []),
    'submitSupporterRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Nat), IDL.Opt(Time)],
        [],
        [],
      ),
    'unfollow' : IDL.Func([IDL.Principal], [], []),
    'unlikePost' : IDL.Func([IDL.Nat], [], []),
    'unlikeProfile' : IDL.Func([IDL.Principal], [], []),
    'vote' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };