/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface GalleryMediaItem {
    title?: string;
    blob: ExternalBlob;
    createdAt: Time;
    description?: string;
    author: Principal;
    mediaType: Variant_video_image;
}
export type Time = bigint;
export interface Comment {
    content: string;
    createdAt: Time;
    authorName?: string;
    author: Principal;
    postId: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Event {
    id: bigint;
    startTime: Time;
    title: string;
    endTime: Time;
    createdAt: Time;
    authorName?: string;
    description: string;
    author: Principal;
    location: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface SupporterRequest {
    displayName: string;
    submittedAt: Time;
    numberOfCoffees?: bigint;
    message: string;
    validUntil?: Time;
}
export interface PostWithCounts {
    likeCount: bigint;
    post: Post;
    commentCount: bigint;
}
export interface PollWithResults {
    question: string;
    createdAt: Time;
    createdBy: Principal;
    results: Array<[bigint, bigint]>;
    isActive: boolean;
    options: Array<PollOption>;
    pollId: bigint;
}
export interface Poll {
    question: string;
    createdAt: Time;
    createdBy: Principal;
    isActive: boolean;
    options: Array<PollOption>;
    pollId: bigint;
}
export interface UserProfileEdit {
    bio: string;
    displayName: string;
    plushieImages: Array<ExternalBlob>;
    links: Array<Link>;
    publicDirectory: boolean;
    avatar?: ExternalBlob;
}
export interface SupporterProfile {
    displayName: string;
    addedAt: Time;
    validUntil?: Time;
}
export interface Post {
    id: bigint;
    title: string;
    video?: ExternalBlob;
    body: string;
    createdAt: Time;
    authorName?: string;
    author: Principal;
}
export interface PollOption {
    optionId: bigint;
    text: string;
}
export interface FollowCounts {
    followers: bigint;
    following: bigint;
}
export interface ModeratedContent {
    id: bigint;
    title: string;
    moderationOutcome: ModerationOutcome;
    video?: ExternalBlob;
    body: string;
    submittedAt: Time;
    author: Principal;
}
export interface Link {
    url: string;
    displayName: string;
}
export interface PostEdit {
    title: string;
    video?: ExternalBlob;
    body: string;
    authorName?: string;
}
export interface UserProfile {
    bio: string;
    displayName: string;
    plushieImages: Array<ExternalBlob>;
    links: Array<Link>;
    publicDirectory: boolean;
    avatar?: ExternalBlob;
}
export enum ModerationOutcome {
    allow = "allow",
    manualReview = "manualReview",
    block = "block"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_video_image {
    video = "video",
    image = "image"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addGalleryMediaItem(mediaType: Variant_video_image, blob: ExternalBlob, title: string | null, description: string | null): Promise<void>;
    approveModerationRequest(id: bigint): Promise<void>;
    approveSupporter(supporter: Principal, validUntil: Time | null): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createComment(postId: bigint, authorName: string | null, content: string): Promise<Comment>;
    createEvent(authorName: string | null, title: string, description: string, location: string, startTime: Time, endTime: Time): Promise<bigint>;
    createModerationRequest(title: string, body: string, video: ExternalBlob | null): Promise<bigint>;
    createPoll(question: string, options: Array<PollOption>): Promise<bigint>;
    deletePost(id: bigint): Promise<void>;
    doesCallerFollow(target: Principal): Promise<boolean>;
    editPost(id: bigint, postEdit: PostEdit): Promise<void>;
    follow(target: Principal): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCommentCounts(postIds: Array<bigint>): Promise<Array<[bigint, bigint]>>;
    getComments(postId: bigint): Promise<Array<Comment>>;
    getEvent(id: bigint): Promise<Event>;
    getFollowCounts(user: Principal): Promise<FollowCounts>;
    getModerationQueue(): Promise<Array<[bigint, ModeratedContent]>>;
    getPoll(id: bigint): Promise<Poll>;
    getPollResults(id: bigint): Promise<PollWithResults>;
    getPost(id: bigint): Promise<Post>;
    getPostLikeCount(postId: bigint): Promise<bigint>;
    getPostsWithCounts(): Promise<Array<PostWithCounts>>;
    getProfileLikeCount(profile: Principal): Promise<bigint>;
    getSupporterRequests(): Promise<Array<[Principal, SupporterRequest]>>;
    getSupporters(): Promise<Array<[Principal, SupporterProfile]>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isPostLikedByCaller(postId: bigint): Promise<boolean>;
    isProfileLikedByCaller(profile: Principal): Promise<boolean>;
    likePost(postId: bigint): Promise<void>;
    likeProfile(profile: Principal): Promise<void>;
    listDirectoryProfiles(): Promise<Array<UserProfile>>;
    listEvents(): Promise<Array<Event>>;
    listGalleryMediaItems(): Promise<Array<GalleryMediaItem>>;
    listPolls(): Promise<Array<Poll>>;
    listPosts(): Promise<Array<Post>>;
    rejectModerationRequest(id: bigint): Promise<void>;
    revokeSupporter(supporter: Principal): Promise<void>;
    saveCallerUserProfile(profileEdit: UserProfileEdit): Promise<void>;
    submitSupporterRequest(displayName: string, message: string, numberOfCoffees: bigint | null, validUntil: Time | null): Promise<void>;
    unfollow(target: Principal): Promise<void>;
    unlikePost(postId: bigint): Promise<void>;
    unlikeProfile(profile: Principal): Promise<void>;
    vote(pollId: bigint, optionId: bigint): Promise<void>;
}
import type { Comment as _Comment, Event as _Event, ExternalBlob as _ExternalBlob, GalleryMediaItem as _GalleryMediaItem, Link as _Link, ModeratedContent as _ModeratedContent, ModerationOutcome as _ModerationOutcome, Post as _Post, PostEdit as _PostEdit, PostWithCounts as _PostWithCounts, SupporterProfile as _SupporterProfile, SupporterRequest as _SupporterRequest, Time as _Time, UserProfile as _UserProfile, UserProfileEdit as _UserProfileEdit, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addGalleryMediaItem(arg0: Variant_video_image, arg1: ExternalBlob, arg2: string | null, arg3: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addGalleryMediaItem(to_candid_variant_n8(this._uploadFile, this._downloadFile, arg0), await to_candid_ExternalBlob_n9(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGalleryMediaItem(to_candid_variant_n8(this._uploadFile, this._downloadFile, arg0), await to_candid_ExternalBlob_n9(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async approveModerationRequest(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveModerationRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveModerationRequest(arg0);
            return result;
        }
    }
    async approveSupporter(arg0: Principal, arg1: Time | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveSupporter(arg0, to_candid_opt_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveSupporter(arg0, to_candid_opt_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createComment(arg0: bigint, arg1: string | null, arg2: string): Promise<Comment> {
        if (this.processError) {
            try {
                const result = await this.actor.createComment(arg0, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg1), arg2);
                return from_candid_Comment_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createComment(arg0, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg1), arg2);
            return from_candid_Comment_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async createEvent(arg0: string | null, arg1: string, arg2: string, arg3: string, arg4: Time, arg5: Time): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createEvent(to_candid_opt_n10(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEvent(to_candid_opt_n10(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async createModerationRequest(arg0: string, arg1: string, arg2: ExternalBlob | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createModerationRequest(arg0, arg1, await to_candid_opt_n17(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createModerationRequest(arg0, arg1, await to_candid_opt_n17(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async createPoll(arg0: string, arg1: Array<PollOption>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createPoll(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPoll(arg0, arg1);
            return result;
        }
    }
    async deletePost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePost(arg0);
            return result;
        }
    }
    async doesCallerFollow(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.doesCallerFollow(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.doesCallerFollow(arg0);
            return result;
        }
    }
    async editPost(arg0: bigint, arg1: PostEdit): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editPost(arg0, await to_candid_PostEdit_n18(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editPost(arg0, await to_candid_PostEdit_n18(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async follow(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.follow(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.follow(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCommentCounts(arg0: Array<bigint>): Promise<Array<[bigint, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCommentCounts(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCommentCounts(arg0);
            return result;
        }
    }
    async getComments(arg0: bigint): Promise<Array<Comment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getComments(arg0);
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getComments(arg0);
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEvent(arg0: bigint): Promise<Event> {
        if (this.processError) {
            try {
                const result = await this.actor.getEvent(arg0);
                return from_candid_Event_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEvent(arg0);
            return from_candid_Event_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFollowCounts(arg0: Principal): Promise<FollowCounts> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowCounts(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowCounts(arg0);
            return result;
        }
    }
    async getModerationQueue(): Promise<Array<[bigint, ModeratedContent]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getModerationQueue();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getModerationQueue();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPoll(arg0: bigint): Promise<Poll> {
        if (this.processError) {
            try {
                const result = await this.actor.getPoll(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPoll(arg0);
            return result;
        }
    }
    async getPollResults(arg0: bigint): Promise<PollWithResults> {
        if (this.processError) {
            try {
                const result = await this.actor.getPollResults(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPollResults(arg0);
            return result;
        }
    }
    async getPost(arg0: bigint): Promise<Post> {
        if (this.processError) {
            try {
                const result = await this.actor.getPost(arg0);
                return from_candid_Post_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPost(arg0);
            return from_candid_Post_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPostLikeCount(arg0: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getPostLikeCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPostLikeCount(arg0);
            return result;
        }
    }
    async getPostsWithCounts(): Promise<Array<PostWithCounts>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPostsWithCounts();
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPostsWithCounts();
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfileLikeCount(arg0: Principal): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfileLikeCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfileLikeCount(arg0);
            return result;
        }
    }
    async getSupporterRequests(): Promise<Array<[Principal, SupporterRequest]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSupporterRequests();
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSupporterRequests();
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSupporters(): Promise<Array<[Principal, SupporterProfile]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSupporters();
                return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSupporters();
            return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isPostLikedByCaller(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isPostLikedByCaller(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isPostLikedByCaller(arg0);
            return result;
        }
    }
    async isProfileLikedByCaller(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isProfileLikedByCaller(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isProfileLikedByCaller(arg0);
            return result;
        }
    }
    async likePost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.likePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.likePost(arg0);
            return result;
        }
    }
    async likeProfile(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.likeProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.likeProfile(arg0);
            return result;
        }
    }
    async listDirectoryProfiles(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.listDirectoryProfiles();
                return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listDirectoryProfiles();
            return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async listEvents(): Promise<Array<Event>> {
        if (this.processError) {
            try {
                const result = await this.actor.listEvents();
                return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listEvents();
            return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async listGalleryMediaItems(): Promise<Array<GalleryMediaItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.listGalleryMediaItems();
                return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listGalleryMediaItems();
            return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async listPolls(): Promise<Array<Poll>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPolls();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPolls();
            return result;
        }
    }
    async listPosts(): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPosts();
                return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPosts();
            return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async rejectModerationRequest(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectModerationRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectModerationRequest(arg0);
            return result;
        }
    }
    async revokeSupporter(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.revokeSupporter(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.revokeSupporter(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfileEdit): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfileEdit_n58(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfileEdit_n58(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitSupporterRequest(arg0: string, arg1: string, arg2: bigint | null, arg3: Time | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitSupporterRequest(arg0, arg1, to_candid_opt_n61(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n11(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitSupporterRequest(arg0, arg1, to_candid_opt_n61(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n11(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async unfollow(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unfollow(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unfollow(arg0);
            return result;
        }
    }
    async unlikePost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unlikePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unlikePost(arg0);
            return result;
        }
    }
    async unlikeProfile(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unlikeProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unlikeProfile(arg0);
            return result;
        }
    }
    async vote(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.vote(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.vote(arg0, arg1);
            return result;
        }
    }
}
function from_candid_Comment_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Comment): Comment {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Event_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Event): Event {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_GalleryMediaItem_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GalleryMediaItem): Promise<GalleryMediaItem> {
    return await from_candid_record_n55(_uploadFile, _downloadFile, value);
}
async function from_candid_ModeratedContent_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ModeratedContent): Promise<ModeratedContent> {
    return await from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_ModerationOutcome_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ModerationOutcome): ModerationOutcome {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
async function from_candid_PostWithCounts_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PostWithCounts): Promise<PostWithCounts> {
    return await from_candid_record_n41(_uploadFile, _downloadFile, value);
}
async function from_candid_Post_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Post): Promise<Post> {
    return await from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_SupporterProfile_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SupporterProfile): SupporterProfile {
    return from_candid_record_n50(_uploadFile, _downloadFile, value);
}
function from_candid_SupporterRequest_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SupporterRequest): SupporterRequest {
    return from_candid_record_n45(_uploadFile, _downloadFile, value);
}
async function from_candid_UserProfile_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): Promise<UserProfile> {
    return await from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): Promise<UserProfile | null> {
    return value.length === 0 ? null : await from_candid_UserProfile_n21(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n24(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    content: string;
    createdAt: _Time;
    authorName: [] | [string];
    author: Principal;
    postId: bigint;
}): {
    content: string;
    createdAt: Time;
    authorName?: string;
    author: Principal;
    postId: bigint;
} {
    return {
        content: value.content,
        createdAt: value.createdAt,
        authorName: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.authorName)),
        author: value.author,
        postId: value.postId
    };
}
async function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    displayName: string;
    plushieImages: Array<_ExternalBlob>;
    links: Array<_Link>;
    publicDirectory: boolean;
    avatar: [] | [_ExternalBlob];
}): Promise<{
    bio: string;
    displayName: string;
    plushieImages: Array<ExternalBlob>;
    links: Array<Link>;
    publicDirectory: boolean;
    avatar?: ExternalBlob;
}> {
    return {
        bio: value.bio,
        displayName: value.displayName,
        plushieImages: await from_candid_vec_n23(_uploadFile, _downloadFile, value.plushieImages),
        links: value.links,
        publicDirectory: value.publicDirectory,
        avatar: record_opt_to_undefined(await from_candid_opt_n25(_uploadFile, _downloadFile, value.avatar))
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    startTime: _Time;
    title: string;
    endTime: _Time;
    createdAt: _Time;
    authorName: [] | [string];
    description: string;
    author: Principal;
    location: string;
}): {
    id: bigint;
    startTime: Time;
    title: string;
    endTime: Time;
    createdAt: Time;
    authorName?: string;
    description: string;
    author: Principal;
    location: string;
} {
    return {
        id: value.id,
        startTime: value.startTime,
        title: value.title,
        endTime: value.endTime,
        createdAt: value.createdAt,
        authorName: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.authorName)),
        description: value.description,
        author: value.author,
        location: value.location
    };
}
async function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    moderationOutcome: _ModerationOutcome;
    video: [] | [_ExternalBlob];
    body: string;
    submittedAt: _Time;
    author: Principal;
}): Promise<{
    id: bigint;
    title: string;
    moderationOutcome: ModerationOutcome;
    video?: ExternalBlob;
    body: string;
    submittedAt: Time;
    author: Principal;
}> {
    return {
        id: value.id,
        title: value.title,
        moderationOutcome: from_candid_ModerationOutcome_n35(_uploadFile, _downloadFile, value.moderationOutcome),
        video: record_opt_to_undefined(await from_candid_opt_n25(_uploadFile, _downloadFile, value.video)),
        body: value.body,
        submittedAt: value.submittedAt,
        author: value.author
    };
}
async function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    video: [] | [_ExternalBlob];
    body: string;
    createdAt: _Time;
    authorName: [] | [string];
    author: Principal;
}): Promise<{
    id: bigint;
    title: string;
    video?: ExternalBlob;
    body: string;
    createdAt: Time;
    authorName?: string;
    author: Principal;
}> {
    return {
        id: value.id,
        title: value.title,
        video: record_opt_to_undefined(await from_candid_opt_n25(_uploadFile, _downloadFile, value.video)),
        body: value.body,
        createdAt: value.createdAt,
        authorName: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.authorName)),
        author: value.author
    };
}
async function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    likeCount: bigint;
    post: _Post;
    commentCount: bigint;
}): Promise<{
    likeCount: bigint;
    post: Post;
    commentCount: bigint;
}> {
    return {
        likeCount: value.likeCount,
        post: await from_candid_Post_n37(_uploadFile, _downloadFile, value.post),
        commentCount: value.commentCount
    };
}
function from_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    displayName: string;
    submittedAt: _Time;
    numberOfCoffees: [] | [bigint];
    message: string;
    validUntil: [] | [_Time];
}): {
    displayName: string;
    submittedAt: Time;
    numberOfCoffees?: bigint;
    message: string;
    validUntil?: Time;
} {
    return {
        displayName: value.displayName,
        submittedAt: value.submittedAt,
        numberOfCoffees: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.numberOfCoffees)),
        message: value.message,
        validUntil: record_opt_to_undefined(from_candid_opt_n46(_uploadFile, _downloadFile, value.validUntil))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    displayName: string;
    addedAt: _Time;
    validUntil: [] | [_Time];
}): {
    displayName: string;
    addedAt: Time;
    validUntil?: Time;
} {
    return {
        displayName: value.displayName,
        addedAt: value.addedAt,
        validUntil: record_opt_to_undefined(from_candid_opt_n46(_uploadFile, _downloadFile, value.validUntil))
    };
}
async function from_candid_record_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: [] | [string];
    blob: _ExternalBlob;
    createdAt: _Time;
    description: [] | [string];
    author: Principal;
    mediaType: {
        video: null;
    } | {
        image: null;
    };
}): Promise<{
    title?: string;
    blob: ExternalBlob;
    createdAt: Time;
    description?: string;
    author: Principal;
    mediaType: Variant_video_image;
}> {
    return {
        title: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.title)),
        blob: await from_candid_ExternalBlob_n24(_uploadFile, _downloadFile, value.blob),
        createdAt: value.createdAt,
        description: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.description)),
        author: value.author,
        mediaType: from_candid_variant_n56(_uploadFile, _downloadFile, value.mediaType)
    };
}
async function from_candid_tuple_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [bigint, _ModeratedContent]): Promise<[bigint, ModeratedContent]> {
    return [
        value[0],
        await from_candid_ModeratedContent_n33(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, _SupporterRequest]): [Principal, SupporterRequest] {
    return [
        value[0],
        from_candid_SupporterRequest_n44(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, _SupporterProfile]): [Principal, SupporterProfile] {
    return [
        value[0],
        from_candid_SupporterProfile_n49(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    allow: null;
} | {
    manualReview: null;
} | {
    block: null;
}): ModerationOutcome {
    return "allow" in value ? ModerationOutcome.allow : "manualReview" in value ? ModerationOutcome.manualReview : "block" in value ? ModerationOutcome.block : value;
}
function from_candid_variant_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    video: null;
} | {
    image: null;
}): Variant_video_image {
    return "video" in value ? Variant_video_image.video : "image" in value ? Variant_video_image.image : value;
}
async function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n24(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Comment>): Array<Comment> {
    return value.map((x)=>from_candid_Comment_n14(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[bigint, _ModeratedContent]>): Promise<Array<[bigint, ModeratedContent]>> {
    return await Promise.all(value.map(async (x)=>await from_candid_tuple_n32(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PostWithCounts>): Promise<Array<PostWithCounts>> {
    return await Promise.all(value.map(async (x)=>await from_candid_PostWithCounts_n40(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, _SupporterRequest]>): Array<[Principal, SupporterRequest]> {
    return value.map((x)=>from_candid_tuple_n43(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, _SupporterProfile]>): Array<[Principal, SupporterProfile]> {
    return value.map((x)=>from_candid_tuple_n48(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Promise<Array<UserProfile>> {
    return await Promise.all(value.map(async (x)=>await from_candid_UserProfile_n21(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Event>): Array<Event> {
    return value.map((x)=>from_candid_Event_n29(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GalleryMediaItem>): Promise<Array<GalleryMediaItem>> {
    return await Promise.all(value.map(async (x)=>await from_candid_GalleryMediaItem_n54(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Post>): Promise<Array<Post>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Post_n37(_uploadFile, _downloadFile, x)));
}
async function to_candid_ExternalBlob_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_PostEdit_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PostEdit): Promise<_PostEdit> {
    return await to_candid_record_n19(_uploadFile, _downloadFile, value);
}
async function to_candid_UserProfileEdit_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfileEdit): Promise<_UserProfileEdit> {
    return await to_candid_record_n59(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Time | null): [] | [_Time] {
    return value === null ? candid_none() : candid_some(value);
}
async function to_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n9(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
async function to_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    video?: ExternalBlob;
    body: string;
    authorName?: string;
}): Promise<{
    title: string;
    video: [] | [_ExternalBlob];
    body: string;
    authorName: [] | [string];
}> {
    return {
        title: value.title,
        video: value.video ? candid_some(await to_candid_ExternalBlob_n9(_uploadFile, _downloadFile, value.video)) : candid_none(),
        body: value.body,
        authorName: value.authorName ? candid_some(value.authorName) : candid_none()
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    displayName: string;
    plushieImages: Array<ExternalBlob>;
    links: Array<Link>;
    publicDirectory: boolean;
    avatar?: ExternalBlob;
}): Promise<{
    bio: string;
    displayName: string;
    plushieImages: Array<_ExternalBlob>;
    links: Array<_Link>;
    publicDirectory: boolean;
    avatar: [] | [_ExternalBlob];
}> {
    return {
        bio: value.bio,
        displayName: value.displayName,
        plushieImages: await to_candid_vec_n60(_uploadFile, _downloadFile, value.plushieImages),
        links: value.links,
        publicDirectory: value.publicDirectory,
        avatar: value.avatar ? candid_some(await to_candid_ExternalBlob_n9(_uploadFile, _downloadFile, value.avatar)) : candid_none()
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_video_image): {
    video: null;
} | {
    image: null;
} {
    return value == Variant_video_image.video ? {
        video: null
    } : value == Variant_video_image.image ? {
        image: null
    } : value;
}
async function to_candid_vec_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n9(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
